version: '3.8'

services:
  # Go WebSocket Server
  linklian-socket:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: linklian-socket
    ports:
      - "4800:4800"
    environment:
      PORT: 4800
      RABBITMQ_URL: amqp://user:password@rabbitmq:5672/
    volumes:
      - .:/app
    working_dir: /app
    restart: unless-stopped